# Much taken from https://github.com/Ezibenroc/PyRoaringBitMap/blob/master/.github/workflows/main.yml
name: memory_allocator

on:
    pull_request:
        types: [opened, synchronize]
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.6, 3.7, 3.8, 3.9]
                architecture: [32bit, 64bt]
        steps:
        - name: Set 32-bit.
          if: ${{ matrix.architecture }} == '32bit'
          env:
              CFLAGS: '-m32'
          run: |
          sudo apt-get install python${{ matrix.python-version }}:i386
        - name: Set up the repository
          uses: actions/checkout@v2
          with:
              submodules: recursive
              fetch-depth: 0
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install setuptools Cython Sphinx flake8
        - name: Freeze pip
          run: |
              pip freeze
        - name: Local build
          run: |
            python setup.py build_ext -i
            python test.py
            git clean -xfd
